Repository NotMyWing/GarrysModAmongUs, pull requests merged in 2020-12, with the labels that each got.

#42 Set default footstep sound to tile
  moon/amongus/gamemode/sh_footsteps.moon
Labels: bug

#44 Make lights sabotage effect look better and less intensive
  moon/amongus/gamemode/sabotages/lights.moon
Labels: enhancement

#75 README badges
  README.md
Labels: enhancement

#73 Add option to disable the taskbar
  src/gamemodes/amongus/gamemode/cl_init.moon
  src/gamemodes/amongus/gamemode/lang/au_default.moon
  src/gamemodes/amongus/gamemode/shared.moon
  src/gamemodes/amongus/gamemode/sv_meeting.moon
  src/gamemodes/amongus/gamemode/sv_net.moon
  src/gamemodes/amongus/gamemode/vgui/vgui_hud.moon
  src/gamemodes/amongus/gamemode/vgui/vgui_showhelp.moon
Labels: enhancement

#62 Add a convar for setting the corpse model
  src/gamemodes/amongus/gamemode/shared.moon
  src/gamemodes/amongus/gamemode/sv_player.moon
Labels: enhancement

#74 Don't reset env_soundcape* entities on cleanup
  src/gamemodes/amongus/gamemode/sv_game.moon
Labels: bug

#76 Add 10 second warning to meetings
  src/gamemodes/amongus/gamemode/vgui/vgui_meeting.moon
  src/sound/au/vote_timer.wav
Labels: enhancement

#78 Add basic CAMI support
  src/gamemodes/amongus/gamemode/cl_init.moon
  src/gamemodes/amongus/gamemode/init.moon
  src/gamemodes/amongus/gamemode/lib/sh_cami.lua
  src/gamemodes/amongus/gamemode/sh_privileges.moon
  src/gamemodes/amongus/gamemode/sv_game.moon
  src/gamemodes/amongus/gamemode/sv_player.moon
  src/gamemodes/amongus/gamemode/vgui/vgui_hud.moon
  src/gamemodes/amongus/gamemode/vgui/vgui_showhelp.moon
Labels: enhancement

#79 Fix eject typing effect for multibyte characters
  src/gamemodes/amongus/gamemode/vgui/vgui_eject.moon
Labels: bug

#80 Add links to README badges
  README.md
Labels: documentation, enhancement

#81 weapons: Fix asteroid centering, apply random y velocity
  src/gamemodes/amongus/gamemode/tasks/clearasteroids.moon
Labels: bug, enhancement

#82 Add French translation by Azellio
  src/gamemodes/amongus/gamemode/lang/au_default_fr.moon
Labels: enhancement, localization

#83 Add Chinese translation
  src/gamemodes/amongus/gamemode/lang/au_default_cn.moon
Labels: enhancement, localization

#84 Discourage direct Lua file modification
  gulpfile.js
  tools/discourageLuaModification.js
Labels: enhancement

#85 Add German Translations
  src/gamemodes/amongus/gamemode/lang/au_default_de.moon
Labels: localization
